### ISSUE TITLE
G2A

### ISSUE THREAD

**Issue by spicyop** [michaelpande/firefox-steam-purchase-options#3]
There should also be a G2A key-store link

**Comment by michaelpande** [comment]
Thanks for your suggestion. I will however not be implementing G2A.

The main reason being idealism. I created the plug-in to give users a alternative to the Steam monopoly and DRM in general. 

I am sceptical to the practices of key reselling. You can read about it for instance on Wikipedia.

See controversies under Wikipedia
https://en.m.wikipedia.org/wiki/G2A

Feel free to request other features in the future :-)
